# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a18781f7c3329e8aa53171c6a15f5117a0090c6a980dc6823c469eab378779ee9c02fb43c6655704e514e7b8fde83aa1839872bb465935fb3f28e083de733d6

test:
  secret_key_base: 804017e11beb219d4e38cbf73babe1741f6ec235f49b169e5ea011cc9f73535023351d4b14cb861f97890fc1aa10ea13c3100b3f9a95e9bdaf05283d257dc84f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
